### ISSUE TITLE
500 Server error "Could not gather sufficient random data"

### ISSUE THREAD

**Issue by zaubererty** [wallabag/docker#63] opened 2017-05-03 13:19 UTC
I have this issue running the docker image version 2.2.2 the image 2.2.1 runs fine.
Cleaned all cookies but did not help.

**Comment by xsteadfastx** [comment] 2017-05-03 13:26
i think its a duplicate of #57 

could you check your kernel version and provide more infos?

**Closed by xsteadfastx** 2017-05-03 13:26 UTC
