### ISSUE TITLE
Arm64 docker image needed

### ISSUE THREAD

**Issue by travelg** [wallabag/docker#266] opened 2021-04-08 09:17 UTC
**Is your feature request related to a problem? Please describe.**
To run wallabag on raspberry pi, Arm64 image is needed.

Thank you.

**Comment by norweeg** [comment] 2021-08-11 18:49
> **Is your feature request related to a problem? Please describe.**
> To run wallabag on raspberry pi, Arm64 image is needed.
> 
> Thank you.

The dockerfile here builds just fine on my RPi.  It would be great if I could pull a pre-built image from docker hub, but it is entirely possible to built it yourself from the dockerfile

**Comment by samyak-jain** [comment] 2021-11-02 17:06
Can we have this as part of the official docker image? We cannot get regular updates if we are building our own image.

**Comment by McMac** [comment] 2022-01-22 19:41
+1 Would be interested too! Trying to move all my services onto a RPi k3s cluster.

**Comment by norweeg** [comment] 2022-04-09 18:34
for anyone who doesn't mind an unofficial build, I built v2.4.3 on my RPi and pushed the image to docker hub https://hub.docker.com/repository/docker/norweeg/wallabag
as it is built directly from this git repo, configuration should be the same as the official image.  The only difference is my build is for ARM64.

**Comment by leolivier** [comment] 2022-05-04 12:23
Hi, I'm myself building a raspberry pi image of wallabag (updated each month) and it's available on docker hub at leolivier/wallabag.
I know Joshua above faced an issue with the last version but for me, it's still working well so probably not linked to the image itself

**Comment by casidiablo** [comment] 2022-05-06 17:54
I am sure those images are just fine, but I just can't phantom installing unofficial images.

This just needs time from the devs. Building/pushing multi arch images is not that complicated (https://docs.docker.com/desktop/multi-arch/), but I understand if this is not a priority.

For now I will just build my own images.

ps. I didn't know you could build docker images by referencing their code in Github! Pretty nice!

**Comment by fdw** [comment] 2022-05-07 10:13
There's already a PR open for this: #284. Maybe we can get this merged?

**Comment by norweeg** [comment] 2022-05-07 15:47
> There's already a PR open for this: #284. Maybe we can get this merged?

looks like it's awaiting testing with the various db connectors.  I can confirm my ARM64 build of this repo works fine with MariaDB

**Comment by samyak-jain** [comment] 2022-06-26 18:54
The official image works for me on arm now :tada:. I think the issue can be closed now?

**Comment by leolivier** [comment] 2022-06-26 20:14
Hi, I confirm the official image is also working on armv7, I will cease maintaining my own rpi image! 🎉🎉🎉

**Comment by Kdecherf** [comment] 2022-06-26 21:58
:+1:

**Closed by Kdecherf** 2022-06-26 21:58 UTC
Labels: Feature
