### ISSUE TITLE
Provisioner fails in task add mariadb user

### ISSUE THREAD

**Issue by m0wer** [wallabag/docker#200] opened 2020-05-15 10:51 UTC
The error is:

```
InvalidPrivsError: unable to parse the MySQL grant string: GRANT USAGE ON entrypoint.sh TO `wallabag`@`%` IDENTIFIED BY PASSWORD '[OMMITED]'
```

Which appears to be related to https://github.com/ansible/ansible/issues/51356. Simply upgrading `ansible` inside the container solves the issue:

```bash
apk add py3-pip
pip3 install --upgrade ansible
```

And then the provisioner can be run again:

```bash
ansible-playbook -i /etc/ansible/hosts /etc/ansible/entrypoint.yml -c local
```

This error avoided the container from starting properly and the logs where showing `HTTP 500` error codes.

**Comment by j0k3r** [comment] 2020-05-15 12:51
So what do we have to do to fix it?
Can you open a PR to fix it?

**Comment by m0wer** [comment] 2020-05-15 13:30
Works fine in `master`/`latest` since the Alpine base image was upgraded to 3.10 (from 3.9) and in that branch of Alpine `ansible` is updated to 2.8 (instead of 2.7). So no changes are needed.

Maybe it would be nice to update the 2.3.8 tag though.

Thanks!

**Comment by Miosame** [comment] 2020-05-26 05:38
Not sure if I have the same issue, but wallabag after the recent update 500's now, can't find any proper logs to confirm what the issue is though - compose logs do not contain anything useful, except maybe mysql complaining about an attempt to connect:

`[Warning] Aborted connection 8 to db: 'unconnected' user: 'unauthenticated' host: 'xxx' (This connection closed normally without authentication)`

**Comment by paulcalabro** [comment] 2020-05-30 06:50
@Miosame Are you pinning to _2.3.8_? If so, that was causing issues for me as well. I saw @m0wer 's command and used _latest_ instead and that resolved my issue. It would be nice if there was a new release since _Docker Bench for Security_ complains about using _latest_ :-) .

**Comment by Miosame** [comment] 2020-05-30 07:01
@paulcalabro I've on purpose set recently containers like wallabag to latest and have watchtower updating them, so sadly I'm on latest from hub at least. No idea how to debug the 500, considering it logs nothing.

**Comment by paulcalabro** [comment] 2020-05-30 21:53
You might be able to troubleshoot the issue by examining _WALLABAG_DIR/var/logs/prod.log_. Additional information can be found [here](https://doc.wallabag.org/en/user/errors_during_fetching.html).

**Comment by Miosame** [comment] 2020-05-30 23:00
@paulcalabro `/var/www/wallabag/var/logs` is empty, no `prod.log`.

**Comment by paulcalabro** [comment] 2020-05-31 04:28
What if you attach to the container and manually run the app?

**Comment by Miosame** [comment] 2020-05-31 04:39
@paulcalabro how would I manually run it? looking at it, it's actually symfony based (so regular php served via webserver) - though sadly enough different from laravel to be alien to me.

Moving temporarily `config_dev.yml` in place of `config_prod.yml` in `/var/www/wallabag/app/config/config_dev.yml` - did sadly not trigger the [hoped for debug page](https://symfony.com/doc/current/controller/error_pages.html) nor cause it to dump any useful messages to docker logs or create any files in the logs folder.

**Comment by Miosame** [comment] 2020-05-31 05:05
@paulcalabro nevermind it was some weird caddy-server issue that was causing it

**Comment by j0k3r** [comment] 2022-11-30 22:08
Ansible has been replaced by shell script few days ago https://github.com/wallabag/docker/pull/307, so I'm closing that issue.

**Closed by j0k3r** 2022-11-30 22:08 UTC
