### ISSUE TITLE
Error report via Docker-Compose

### ISSUE THREAD

**Issue by starsareintherose** [wallabag/docker#252] opened 2021-02-25 11:27 UTC
```
[WARNING]: Found both group and host with same name: localhost
[WARNING]: Platform linux on host localhost is using the discovered Python
interpreter at /usr/bin/python3, but future installation of another Python
interpreter could change this. See https://docs.ansible.com/ansible/2.9/referen
ce_appendices/interpreter_discovery.html for more information.
[WARNING]: Module did not set no_log for update_password
```
I have changed the hostname via docker and run, but the error is still here.

**Comment by j0k3r** [comment] 2021-02-25 12:02
You don't need to open multiple issue, one is enough.

Duplicate of #251

**Closed by j0k3r** 2021-02-25 12:02 UTC
