### ISSUE TITLE
composer install quirks

### ISSUE THREAD

**Issue by fradav** [wallabag/docker#38] opened 2016-11-29 16:28 UTC
the composer install is missing a `-d memory_limit=-1` argument (for php) and a `--no-interaction`  argument to be able to finish.

**Comment by xsteadfastx** [comment] 2016-11-29 16:32
where? the image is building fine and works? how can i reproduce the problem?

**Comment by fradav** [comment] 2016-11-29 16:38
Where, in the dockerfile :
`RUN cd /var/www/wallabag \
 && SYMFONY_ENV=prod composer install --no-dev -o --prefer-dist` 
No the image isn't building since composer crashes at this point without the aforementioned arguments
To reproduce the problem, add:
```
    build:
      context: .
      dockerfile: Dockerfile
```
in the `docker-compose.yml`

**Comment by xsteadfastx** [comment] 2016-11-30 08:59
i cant reproduce it. i always build the image byself to test it... plus travis is building it and docker hub too. did you change anything else in the Dockerfile?

**Comment by fradav** [comment] 2016-11-30 10:01
Just this: `WALLABAG_VERSION=2.2`
Sorry I forgot about this, since I need a feature only available in 2.2

**Comment by xsteadfastx** [comment] 2016-11-30 10:52
version 2.2 has no official release right now. we have to wait to see what changed to get it working. but thanks for your information already.

**Comment by yekibud** [comment] 2016-12-09 18:48
@fradav I'm also trying to build 2.2 to get image storage working.  Were you able to build and run successfully with those parameters?  I tried and get the following error when I try to hit the site.  The stack trace does not point to an obvious error in the wallabag source, and I'm not a PHP guy.  It would be nice to test out 2.2 locally in a container but I'll try a VM install if there's not an easy and obvious fix.

```
[error] 244#244: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException: You have requested a non-existent parameter "database_charset". Did you mean one of these: "database_host", "database_port", "database_name", "database_user", "database_socket"? in /var/www/wallabag/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php:84
#0 /var/www/wallabag/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php(200): Symfony\Component\DependencyInjection\ParameterBag\ParameterBag->get('database_charse...')
#1 /var/www/wallabag/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php(171): Symfony\Component\DependencyInjection\ParameterBag\ParameterBag->resolveString('%database_chars...', Array)
#2 /var/www/wallabag/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php(161): Symfony\Component\DependencyI" while reading response header from upstream, client: ::ffff:172.17.0.1, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "localhost"
```

**Comment by fradav** [comment] 2017-01-30 21:39
@yekibud I got the exact same error than you, so your guess is as good as mine at this point. I don't know if it is docker environnement problem or simply a 2.2 bug.

**Comment by j0k3r** [comment] 2017-01-31 06:21
The PR for 2.2 is not yet ready https://github.com/wallabag/docker/pull/47

**Comment by xsteadfastx** [comment] 2017-01-31 10:54
Any ideas about the error? I can't read anything out of it.

**Comment by xsteadfastx** [comment] 2017-01-31 15:37
could someone try this branch: https://github.com/xsteadfastx/wallabag/tree/version-2.2.1

**Comment by j0k3r** [comment] 2017-02-01 10:08
This might be fixed with the last merge.

**Comment by yekibud** [comment] 2017-05-08 17:35
Not sure where the original issue got fixed, but definitely working in merge request for #65.

**Comment by j0k3r** [comment] 2017-05-09 05:23
Great! Thanks

**Closed by j0k3r** 2017-05-09 05:23 UTC
